#config/schedule.yml

metrics_job:
  cron: "30 1 * * *"
  class: "MetricsGenerationWorker"
  queue: metrics

change_active_step_job:
  cron: "*/15 * * * *"
  class: "ChangeActiveStepWorker"
  queue: default
