# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  # hacking user private invitations, use false to avoid sending invitation 
  # use a mail template identifier otherwise
  # 
  private_invites:
    localhost:
      default: false # invite_private_user
      assemblies:
        numquam-officia: invite_private_user
        perferendis-voluptatem: world_council
    www.uclgmeets.org:
      default: false
      assemblies: 
        WorldCouncil: world_council
    staging.uclgmeets.org:
      default: false
      assemblies: 
        WorldCouncil: world_council
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  omniauth:
    facebook:
      # It must be a boolean. Remember ENV variables doesn't support booleans.
      enabled: false
      app_id: <%= ENV["OMNIAUTH_FACEBOOK_APP_ID"] %>
      app_secret: <%= ENV["OMNIAUTH_FACEBOOK_APP_SECRET"] %>
    twitter:
      enabled: false
      api_key: <%= ENV["OMNIAUTH_TWITTER_API_KEY"] %>
      api_secret: <%= ENV["OMNIAUTH_TWITTER_API_SECRET"] %>
    google_oauth2:
      enabled: false
      icon_path: decidim/brands/google.svg
      client_id: <%= ENV["OMNIAUTH_GOOGLE_CLIENT_ID"] %>
      client_secret: <%= ENV["OMNIAUTH_GOOGLE_CLIENT_SECRET"] %>
  maps:
    here_api_key: <%= ENV["GEOCODER_API_KEY"] %>
  etherpad:
    server: <%= ENV["ETHERPAD_SERVER"] %>
    api_key: <%= ENV["ETHERPAD_API_KEY"] %>
    api_version: "1.2.1"
  uclg:
    conferences:
      - slug: AnnualRetreat2021
        page_background: uclg/Water_Mark.png
        soundcloud_url: "https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/1201873432&color=%23ff0000&hide_related=true&show_comments=false&show_user=false&show_reposts=false&show_teaser=true&visual=true"
        video_url:
          en: https://www.youtube.com/embed/kpzgUq5BDnY
          es: https://www.youtube.com/embed/byV5O_pAK8c
          fr: https://www.youtube.com/embed/8O1DoHX4c-8
      - slug: ProgramEB21
        page_background: uclg/water_mark_2.png
      - slug: LRGdays2021
        video_url:
          en: https://www.youtube.com/embed/kpzgUq5BDnY
          es: https://www.youtube.com/embed/kpzgUq5BDnY
          fr: https://www.youtube.com/embed/kpzgUq5BDnY
development:
  <<: *default
  secret_key_base: 976349832ab51a8fcd5f5e322f7d88ca659853c4f4cfee68c16a03489ba88ec7eac56213186d5aa51f0ae041fdeae873d630fd2ae045ab5323deb2f04272d16b
  omniauth:
    developer:
      enabled: true
      icon: phone
  uclg:
    conferences:
    - slug: AnnualRetreat2021
      page_background: uclg/Water_Mark.png
      soundcloud_url: "https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/1201873432&color=%23ff0000&hide_related=true&show_comments=false&show_user=false&show_reposts=false&show_teaser=true&visual=true"
      video_url:
        en: https://www.youtube.com/embed/kpzgUq5BDnY
        es: https://www.youtube.com/embed/byV5O_pAK8c
        fr: https://www.youtube.com/embed/8O1DoHX4c-8
    - slug: ProgramEB21
      page_background: uclg/water_mark_2.png
    - slug: LRGdays2021
      video_url:
        en: https://www.youtube.com/embed/kpzgUq5BDnY
        es: https://www.youtube.com/embed/kpzgUq5BDnY
        fr: https://www.youtube.com/embed/kpzgUq5BDnY
test:
  <<: *default
  secret_key_base: 47aa65984e28508c235164c8af49db4c838654379eeccad64ff680f6dda6a99930955f390aa06852bfb4e87433da04a5666d938c67955c0ef6e90a3cd2273c39
  geocoder:
    here_api_key: fake-here-api-key
  omniauth:
    facebook:
      enabled: true
      app_id: fake-facebook-app-id
      app_secret: fake-facebook-app-secret
    twitter:
      enabled: true
      api_key: fake-twitter-api-key
      api_secret: fake-twitter-api-secret
    google_oauth2:
      enabled: true
      client_id:
      client_secret:
  uclg:
    conferences:
      - slug: test-conference
        page_background: uclg/Water_Mark.png
        soundcloud_url: "https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/1201873432&color=%23ff0000&hide_related=true&show_comments=false&show_user=false&show_reposts=false&show_teaser=true&visual=true"
        video_url:
          en: https://www.youtube.com/embed/kpzgUq5BDnY
          es: https://www.youtube.com/embed/byV5O_pAK8c
          fr: https://www.youtube.com/embed/8O1DoHX4c-8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  smtp_username: <%= ENV["SMTP_USERNAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>
  smtp_address: <%= ENV["SMTP_ADDRESS"] %>
  smtp_domain: <%= ENV["SMTP_DOMAIN"] %>
  smtp_port: "587"
  smtp_starttls_auto: true
  smtp_authentication: "plain"
